### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by kanudas** [CygnusNetworks/check_ruckus_vsz#3]
Hi,

Trying out your plugin towards a Virtual SmartZone from CentOS 7.
Getting a few errors and not the expected output

./check_ruckus_vsz -H x.x.x.x -C MyCommunity -v
RUCKUSVSZ UNKNOWN: TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "./check_ruckus_vsz", line 407, in main
    check.main(args.verbose, timeout=args.timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 129, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/platform/posix.py", line 17, in with_timeout
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 80, in _evaluate_resource
    for metric in metrics:
  File "./check_ruckus_vsz", line 222, in probe
    scgap_mac_parts = list("%02X" % ord(x) for x in scgap_mac_bytes)
TypeError: 'NoneType' object is not iterable

Any help is greatly appriciated.

Best regards,

**Comment by cygnusb** [comment]
Can you please make snmpwalk on the ruckus controller. You need to copy all *.txt files from ruckus_vsz_snmp/ directory to ~/.snmp/mibs/ dir. And add `mibs +ALL` to ~./snmp/snmp.conf

When this is setup, you will be able to run:
`snmpwalk -v2c -cYOUR_COMMUNITY YOUR_RUCKUS_IP RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac`

That should give a clue, what is happening here. My guess is that Ruckus changed their mibs. Which controller version are you using?

**Comment by kanudas** [comment]
Hi!
I'm starting to suspect they changed their MIBS as well.
Version we are using: 5.1.0.0.496

Output of snmpwalk:
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.)3'.128 = STRING: 18:4b:d:29:33:80
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.32 = STRING: 18:4b:d:2a:9c:20
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.96 = STRING: 18:4b:d:2a:9c:60
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.160 = STRING: 18:4b:d:2a:a3:a0
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.208 = STRING: 18:4b:d:2a:a4:d0
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.16 = STRING: 18:4b:d:2a:a5:10
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.160 = STRING: 18:4b:d:2a:a5:a0
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.224 = STRING: 18:4b:d:2a:a5:e0
RUCKUS-SCG-WLAN-MIB::ruckusSCGAPMac.'..K.*.'.48 = STRING: 18:4b:d:2a:a6:30
....

Best regards,

**Comment by cygnusb** [comment]
Does not look different here on my side. Are you sure you have used the correct SNMP community with the same persmissions, when using the plugin?

**Comment by cygnusb** [comment]
Can you run the plugin with multiple -vvv ?

**Comment by kanudas** [comment]
Hi, Thanks for respons. Of course, here is output (Please note the output is 12684 linues but it as you can expect it just continues with previous output); 

`./check_ruckus_vsz -H X.X.X.X -C XXXX -vvv > ./troubleshootlog.log

RUCKUSVSZ UNKNOWN: TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "./check_ruckus_vsz", line 407, in main
    check.main(args.verbose, timeout=args.timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 129, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/platform/posix.py", line 17, in with_timeout
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 80, in _evaluate_resource
    for metric in metrics:
  File "./check_ruckus_vsz", line 222, in probe
    scgap_mac_parts = list("%02X" % ord(x) for x in scgap_mac_bytes)
TypeError: 'NoneType' object is not iterable
Probing Ruckus SCG device X.X.X.X through SNMP
PySNMP version is 4.4.12 - pyasn1 version is 0.4.8
Queried Ruckus SCG device X.X.X.X through SNMP - device is reachable
Found Sysname vSZ-XX-XX-XX and sysdescr SmartCell Gateway
Starting SNMP polling of host X.X.X.X
parsing entry ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.2.1.1.3.0]>), <TimeTicks value object, subtypeSpec <ConstraintsIntersection object, consts $
oid/value is 1.3.6.1.2.1.1.3.0=<TimeTicks value object, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 4294967295>>, tagSet <TagSet object, tags 64:0:3>, payload [23$
parsing entry ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.4.1.2505...1.3.1.1.1.15.5.0]>), <Counter64 value object, subtypeSpec <ConstraintsIntersecti$
oid/value is 1.3.6.1.4.1.25053.1.3.1.1.1.15.5.0=<Counter64 value object, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 18446744073709551615L>>, tagSet <TagSet objec$
Device X.X.X.X number of received packets is 9024490057
parsing entry ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.4.1.2505...1.3.1.1.1.15.6.0]>), <Counter64 value object, subtypeSpec <ConstraintsIntersecti$
oid/value is 1.3.6.1.4.1.25053.1.3.1.1.1.15.6.0=<Counter64 value object, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 18446744073709551615L>>, tagSet <TagSet objec$
Device X.X.X.X number of received bytes is 3131392075992
parsing entry ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.4.1.2505...1.3.1.1.1.15.7.0]>), <Counter64 value object, subtypeSpec <ConstraintsIntersecti$
oid/value is 1.3.6.1.4.1.25053.1.3.1.1.1.15.7.0=<Counter64 value object, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 18446744073709551615L>>, tagSet <TagSet objec$
Device X.X.X.X number of received multicast packets is 252613316
parsing entry ObjectType(ObjectIdentity(<ObjectName value object, tagSet <TagSet object, tags 0:0:6>, payload [1.3.6.1.4.1.2505...1.3.1.1.1.15.8.0]>), <Counter64 value object, subtypeSpec <ConstraintsIntersecti$
oid/value is 1.3.6.1.4.1.25053.1.3.1.1.1.15.8.0=<Counter64 value object, subtypeSpec <ConstraintsIntersection object, consts <ValueRangeConstraint object, consts 0, 18446744073709551615L>>, tagSet <TagSet objec$
Device X.X.X.X number of sent packets is 20640168882
...`

**Comment by cygnusb** [comment]
Please execute a git pull before running the plugin. And please attach the full output

**Comment by kanudas** [comment]
Hi! Sorry, ran a git clone and got the following Output from a regular now:

./check_ruckus_vsz -H X.X.X.X -C xxxx
RUCKUSVSZ OK - 0 stations connected AP:(monitored 0, connected 0, configured 0) DISK:(free 266.4 / 292.1 GB -- 91.2%) MEM:(free 9.7 / 31.5 GB -- 30.9%) LOAD:(1min 1.17, 5min 1.09, 15min 1.11) | data_free=266.398685455;40:;30: data_free_percent=91.1982090497 data_size=292.109558105 load_15min=1.11;3;4 load_1min=1.17;5;10 load_5min=1.09;4;6 mem_free=9.71027755737;4:;2: mem_free_percent=30.8557790575 mem_size=31.4698829651 num_ap=0 num_ap_configured=0 num_ap_connected=0 num_sta=0 stats_rx_bytes=3259978711549c stats_rx_multicast=258866611c stats_rx_pkts=9321283168c stats_tx_bytes=18148879926139c stats_tx_fail=0c stats_tx_multicast=0c stats_tx_pkts=21232288291c stats_tx_retry=0c sysuptime=394382;@120

Which seems alot bettter but it still says 0 on most areas which doesnt seem to be correct. Also attaching full -vvv output.
[output.log](https://github.com/CygnusNetworks/check_ruckus_vsz/files/4040650/output.log)

Best regards,

**Comment by cygnusb** [comment]
Ok. The issue seems to be that on your installation the script cannot find the installed mibs. And that is causing this issue. I am having the same issue, when I am installing through `python setup.py install`. When using the Debian packaging and Debian packaged version it works fine.

**Comment by cygnusb** [comment]
I am not sure how to fix this. Normally a zip_safe=False in setup.py should do the trick, but that did not solve the issue.

**Comment by cygnusb** [comment]
Please try with the lastest commit. That should hopefully solve the issue.

**Comment by kanudas** [comment]
Hi!

Tried running with the New Commit.

./check_ruckus_vsz -H 10.0.0.4 -C d1zparc_ninja_rapporter -v
RUCKUSVSZ UNKNOWN: AddressValueError: '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "./check_ruckus_vsz", line 415, in main
    check.main(args.verbose, timeout=args.timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 129, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/platform/posix.py", line 17, in with_timeout
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 80, in _evaluate_resource
    for metric in metrics:
  File "./check_ruckus_vsz", line 263, in probe
    scgap_ipv6addr = ipaddress.IPv6Address(scgaptable['RUCKUS-SCG-WLAN-MIB::ruckusSCGAPIPV6Addr.%s' % scgapmac])
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 2026, in __init__
    self._check_packed_address(address, 16)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 553, in _check_packed_address
    expected_len, self._version))
AddressValueError: '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

**Comment by kanudas** [comment]
Hi, 

Thanks for your respons.

Tried with the latest commit but getting a new error now,

./check_ruckus_vsz -H X.X.X.X -C XXXX -v
RUCKUSVSZ UNKNOWN: AddressValueError: '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "./check_ruckus_vsz", line 415, in main
    check.main(args.verbose, timeout=args.timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 121, in main
    runtime.execute(self, verbose, timeout)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 129, in execute
    with_timeout(self.timeout, self.run, check)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/platform/posix.py", line 17, in with_timeout
    func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/runtime.py", line 118, in run
    check()
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 106, in __call__
    self._evaluate_resource(resource)
  File "/usr/lib/python2.7/site-packages/nagiosplugin-1.3.2-py2.7.egg/nagiosplugin/check.py", line 80, in _evaluate_resource
    for metric in metrics:
  File "./check_ruckus_vsz", line 263, in probe
    scgap_ipv6addr = ipaddress.IPv6Address(scgaptable['RUCKUS-SCG-WLAN-MIB::ruckusSCGAPIPV6Addr.%s' % scgapmac])
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 2026, in __init__
    self._check_packed_address(address, 16)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 553, in _check_packed_address
    expected_len, self._version))
AddressValueError: '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?

[output2.log](https://github.com/CygnusNetworks/check_ruckus_vsz/files/4044714/output2.log)

Thanking lots for your assistance,
Best regards,

**Comment by cygnusb** [comment]
Thanks for testing again. I cleaned up the code a bit bit and improved the ip address handling, where this seem to fail on Python 2. Please retry with the latest commit.

**Comment by kanudas** [comment]
Hi, no need to thank me, I'm grateful for being able to utilize your check and assistance. Thanks greatly.
Ran again with latest commit and it seems to be giving the expected output.

./check_ruckus_vsz -H X.X.X.X -C XXXXXXXXXX
RUCKUSVSZ OK - 0 stations connected AP:(monitored 178, connected 0, configured 0) DISK:(free 266.6 / 292.1 GB -- 91.3%) MEM:(free 8.1 / 31.5 GB -- 25.6%) LOAD:(1min 1.16, 5min 1.15, 15min 1.17) | data_free=266.643341064;40:;30: data_free_percent=91.2819637926 data_size=292.109558105 load_15min=1.17;3;4 load_1min=1.16;5;10 load_5min=1.15;4;6 mem_free=8.05781173706;4:;2: mem_free_percent=25.6048354104 mem_size=31.4698829651 num_ap=178 num_ap_configured=0 num_ap_connected=0 num_sta=0 stats_rx_bytes=3312522820271c stats_rx_multicast=260899302c stats_rx_pkts=9405776027c stats_tx_bytes=18270480119092c stats_tx_fail=0c stats_tx_multicast=0c stats_tx_pkts=21388692948c stats_tx_retry=0c sysuptime=395715;@120

Looks alright right?

Thanks alot!

Best regards,

**Comment by cygnusb** [comment]
Depends. It reports zero stations connected and zero APs connected. So if its a testsystem not having any working APs connected, then this would be ok. If its a production system, it should report something like:
` ...293 stations connected AP:(monitored 56, connected 54, configured 54)...`
 
I would need a full output again, if the output is not the expected output. My guess is that all APs are skipped, due to a parsing error in the IPs. I simply skip the APs, if there is a failure. I should propably change this back to fail completely.

**Comment by cygnusb** [comment]
And in addition you might also check the different check_ruckus_ap calls, which check the statistics of each AP individually.

**Comment by kanudas** [comment]
Hi, Allright!

Posting new logs:
[output3.log](https://github.com/CygnusNetworks/check_ruckus_vsz/files/4045489/output3.log)

Hmm. Is there a way to run the check_ruckus_ap calls against all aps simoultaniously with dynamic input do you think?

Thanks for your continued assistance,
Best regards.

**Comment by cygnusb** [comment]
> Hmm. Is there a way to run the check_ruckus_ap calls against all aps simoultaniously with dynamic input do you think?

This is not working since you would have dynamic changes of performance data (when APs are added or removed), which Nagios cannot deal with if you are using a rrd backend.
In addition the output will grow to big and nagios has a limit of performance data, which can be parsed on a single call. 

You can simply generate Nagios Configs for all APs using:
`./check_ruckus_vsz -H 10.0.0.1 -C public -o /etc/nagios3/ruckus.d`

We do this in a cronjob. This will check all aps with a single check

**Comment by cygnusb** [comment]
> Posting new logs:
> [output3.log](https://github.com/CygnusNetworks/check_ruckus_vsz/files/4045489/output3.log)

As I expected, it seems that all APs are skipped, since your Version reports missing IPV6 IPs as empty string and our version reports these as `::`. Will add a handling for this.

```
Caught exception on parsing ips '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object? - skipping ap 20:58:69:3D:12:60
Traceback (most recent call last):
  File "./check_ruckus_vsz", line 268, in probe
    scgap_ipv6addr = ipaddress.IPv6Address(scgaptable['RUCKUS-SCG-WLAN-MIB::ruckusSCGAPIPV6Addr.%s' % mac_numeric])
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 2026, in __init__
    self._check_packed_address(address, 16)
  File "/usr/lib/python2.7/site-packages/ipaddress.py", line 553, in _check_packed_address
    expected_len, self._version))
AddressValueError: '' (len 0 != 16) is not permitted as an IPv6 address. Did you pass in a bytes (str in Python 2) instead of a unicode object?
```

**Comment by cygnusb** [comment]
Pushed to github

**Comment by kanudas** [comment]
Hi! Thanks for yet another Effort!

./check_ruckus_vsz -H X.X.X.X -C XXXXXXXX
RUCKUSVSZ WARNING - load_1min is 5.16 (outside range 0:5) - 213 stations connected AP:(monitored 178, connected 150, configured 150) DISK:(free 266.4 / 292.1 GB -- 91.2%) MEM:(free 8.4 / 31.5 GB -- 26.6%) LOAD:(1min 5.16, 5min 4.68, 15min 3.77) | data_free=266.443809509;40:;30: data_free_percent=91.2136566969 data_size=292.109558105 load_15min=3.77;3;4 load_1min=5.16;5;10 load_5min=4.68;4;6 mem_free=8.38164520264;4:;2: mem_free_percent=26.6338620068 mem_size=31.4698829651 num_ap=178 num_ap_configured=150 num_ap_connected=150 num_sta=213 stats_rx_bytes=3324514753766c stats_rx_multicast=261556337c stats_rx_pkts=9435499634c stats_tx_bytes=18323462624080c stats_tx_fail=0c stats_tx_multicast=0c stats_tx_pkts=21450939297c stats_tx_retry=0c sysuptime=395959;@120

This looks great now!

Here is full VVV if you wanna look at it:

[output4.log](https://github.com/CygnusNetworks/check_ruckus_vsz/files/4046486/output4.log)

Thanks greatly for your help today!

Best regards,

**Comment by cygnusb** [comment]
Ok great. Looks good now.
