### ISSUE TITLE
Argument error on paramter, --domain

### ISSUE THREAD

**Issue by emilnd** [CygnusNetworks/check_ruckus_vsz#4]
Hi.

I'm having trouble running your check.

System: Centos 6
Python versions:
* Python 2.6 (yum)
* ActivePython 2.7
* ActivePython 3.7

`UNKNOWN: IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/nagiosplugin/runtime.py", line 44, in wrapper
    return func(*args, **kwds)
  File "./check_ruckus_vsz.py", line 344, in main
    argp.add_argument('--domain', help='Domain name for Nagios hostnames', default=socket.getfqdn().split('.', 1)[1])
IndexError: list index out of range
`
This happens booth if I specify the parameter and not.
Examples I've tried:
* --domain "hostname.balbla.local"
* --domain "balbla.local"
* --domain="hostname.balbla.local"
* --domain="balbla.local"

I'm getting this on all the different python-versions listed above. When I try it on my own Ubuntu 20.04 machine I've no problems, but on that one I can't reach the central nagios to do a full test, aswell as the ruckus-stuff them self.

When I do **socket.getfqdn().split('.', 1)[1]** manaully in Python it works as expected. Though the machine it self will only return it's hostname as it don't really belong to one.

Questions:
* What versions of python is the script intended to be run with.
* Do the machine need to belong to a domain of some sort so that the parameter get what it kinda expects?

**Comment by cygnusb** [comment]
We are running this mainly on Python 3 now. But it was working on Python 2.6 and 2.7 before.

Can you please provide output of:
`hostname -f (on shell)`

and 

`socket.getfqdn()`

in Python?

I think we need to change this code to have more proper error checking, if the local domain cannot be determined manually. Will add this in a few moments.

**Comment by cygnusb** [comment]
See latest commit for better error handling, when domainname cannot be determined automatically

**Comment by emilnd** [comment]
Hi!

`hostname -f
sina01`

python 2.6.6
`>>> import socket
>>> socket.getfqdn()
'sina01'
`

I've tried the code with your commit (manually) and I came much further in the execution now. However, since I use this ActivePython-stuff at the moment there is problems with modules. I need to talk to my colleague how we are going to tackle this. It is not the first time we get stuck on these kind of problems with older Centos.

**Comment by cygnusb** [comment]
Ok, issue is/was that your system does not have a proper setup FQDN name. See: https://serverfault.com/questions/331936/setting-the-hostname-fqdn-or-short-name for details and discussion about this.

Latest fix will ensure in this case, that domainname set to to .local for generating nagios configs and does not generate a exception.
